# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newMain.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1688, 1134)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1853, 1141))
        self.stackedWidget.setObjectName("stackedWidget")
        self.mainPage = QtWidgets.QWidget()
        self.mainPage.setObjectName("mainPage")
        self.filterBox = QtWidgets.QWidget(self.mainPage)
        self.filterBox.setGeometry(QtCore.QRect(0, 0, 341, 1121))
        self.filterBox.setMinimumSize(QtCore.QSize(0, 0))
        self.filterBox.setStyleSheet("background-color: #A5BECF")
        self.filterBox.setObjectName("filterBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.filterBox)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.filterBox)
        self.scrollArea.setStyleSheet("background-color: #A5BECF;\n"
"border: #A5BECF")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 341, 1127))
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setContentsMargins(13, -1, 13, -1)
        self.gridLayout_3.setHorizontalSpacing(9)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.title = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(35)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.gridLayout_3.addWidget(self.title, 0, 1, 1, 1)
        self.completionButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.completionButton.setStyleSheet("background-color: #F3F5F4;\n"
"border-radius: 10px;")
        self.completionButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../bottom-arrow-icon-15.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.completionButton.setIcon(icon)
        self.completionButton.setObjectName("completionButton")
        self.gridLayout_3.addWidget(self.completionButton, 3, 2, 1, 1)
        self.dayTItle = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        font.setPointSize(12)
        self.dayTItle.setFont(font)
        self.dayTItle.setObjectName("dayTItle")
        self.gridLayout_3.addWidget(self.dayTItle, 1, 1, 1, 1)
        self.dayButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.dayButton.setStyleSheet("background-color: #F3F5F4;\n"
"border-radius: 10px;")
        self.dayButton.setText("")
        self.dayButton.setIcon(icon)
        self.dayButton.setObjectName("dayButton")
        self.gridLayout_3.addWidget(self.dayButton, 1, 2, 1, 1)
        self.resetButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.resetButton.setStyleSheet("background-color: #F3F5F4;\n"
"border-radius: 10px;")
        self.resetButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../kisspng-computer-icons-reset-clip-art-clothes-button-5abcca10d11d47.5817533415223219368565.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resetButton.setIcon(icon1)
        self.resetButton.setObjectName("resetButton")
        self.gridLayout_3.addWidget(self.resetButton, 0, 2, 1, 1)
        self.completionTitle = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        font.setPointSize(12)
        self.completionTitle.setFont(font)
        self.completionTitle.setObjectName("completionTitle")
        self.gridLayout_3.addWidget(self.completionTitle, 3, 1, 1, 1)
        self.yearButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.yearButton.setStyleSheet("background-color: #F3F5F4;\n"
"border-radius: 10px;")
        self.yearButton.setText("")
        self.yearButton.setIcon(icon)
        self.yearButton.setObjectName("yearButton")
        self.gridLayout_3.addWidget(self.yearButton, 7, 2, 1, 1)
        self.genreButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.genreButton.setStyleSheet("background-color: #F3F5F4;\n"
"border-radius: 10px;")
        self.genreButton.setText("")
        self.genreButton.setIcon(icon)
        self.genreButton.setObjectName("genreButton")
        self.gridLayout_3.addWidget(self.genreButton, 5, 2, 1, 1)
        self.ratingTitle = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        font.setPointSize(12)
        self.ratingTitle.setFont(font)
        self.ratingTitle.setObjectName("ratingTitle")
        self.gridLayout_3.addWidget(self.ratingTitle, 9, 1, 1, 1)
        self.genreTitle = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        font.setPointSize(12)
        self.genreTitle.setFont(font)
        self.genreTitle.setObjectName("genreTitle")
        self.gridLayout_3.addWidget(self.genreTitle, 5, 1, 1, 1)
        self.yearTitle = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        font.setPointSize(12)
        self.yearTitle.setFont(font)
        self.yearTitle.setObjectName("yearTitle")
        self.gridLayout_3.addWidget(self.yearTitle, 7, 1, 1, 1)
        self.yearFrame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.yearFrame.setStyleSheet("")
        self.yearFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.yearFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.yearFrame.setObjectName("yearFrame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.yearFrame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.year2020 = QtWidgets.QCheckBox(self.yearFrame)
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        self.year2020.setFont(font)
        self.year2020.setObjectName("year2020")
        self.gridLayout_6.addWidget(self.year2020, 0, 0, 1, 1)
        self.year2019 = QtWidgets.QCheckBox(self.yearFrame)
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        self.year2019.setFont(font)
        self.year2019.setObjectName("year2019")
        self.gridLayout_6.addWidget(self.year2019, 1, 0, 1, 1)
        self.year2018 = QtWidgets.QCheckBox(self.yearFrame)
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        self.year2018.setFont(font)
        self.year2018.setObjectName("year2018")
        self.gridLayout_6.addWidget(self.year2018, 2, 0, 1, 1)
        self.year2017 = QtWidgets.QCheckBox(self.yearFrame)
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        self.year2017.setFont(font)
        self.year2017.setObjectName("year2017")
        self.gridLayout_6.addWidget(self.year2017, 3, 0, 1, 1)
        self.year2016 = QtWidgets.QCheckBox(self.yearFrame)
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        self.year2016.setFont(font)
        self.year2016.setObjectName("year2016")
        self.gridLayout_6.addWidget(self.year2016, 4, 0, 1, 1)
        self.gridLayout_3.addWidget(self.yearFrame, 8, 1, 1, 1)
        self.genreFrame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.genreFrame.setStyleSheet("")
        self.genreFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.genreFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.genreFrame.setObjectName("genreFrame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.genreFrame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.loveComedy = QtWidgets.QCheckBox(self.genreFrame)
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        self.loveComedy.setFont(font)
        self.loveComedy.setObjectName("loveComedy")
        self.gridLayout_4.addWidget(self.loveComedy, 0, 0, 1, 1)
        self.daily = QtWidgets.QCheckBox(self.genreFrame)
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        self.daily.setFont(font)
        self.daily.setObjectName("daily")
        self.gridLayout_4.addWidget(self.daily, 1, 0, 1, 1)
        self.action = QtWidgets.QCheckBox(self.genreFrame)
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        self.action.setFont(font)
        self.action.setObjectName("action")
        self.gridLayout_4.addWidget(self.action, 2, 0, 1, 1)
        self.thriller = QtWidgets.QCheckBox(self.genreFrame)
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        self.thriller.setFont(font)
        self.thriller.setObjectName("thriller")
        self.gridLayout_4.addWidget(self.thriller, 3, 0, 1, 1)
        self.fantasy = QtWidgets.QCheckBox(self.genreFrame)
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        self.fantasy.setFont(font)
        self.fantasy.setObjectName("fantasy")
        self.gridLayout_4.addWidget(self.fantasy, 4, 0, 1, 1)
        self.detective = QtWidgets.QCheckBox(self.genreFrame)
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        self.detective.setFont(font)
        self.detective.setObjectName("detective")
        self.gridLayout_4.addWidget(self.detective, 5, 0, 1, 1)
        self.sport = QtWidgets.QCheckBox(self.genreFrame)
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        self.sport.setFont(font)
        self.sport.setObjectName("sport")
        self.gridLayout_4.addWidget(self.sport, 6, 0, 1, 1)
        self.gridLayout_3.addWidget(self.genreFrame, 6, 1, 1, 1)
        self.ratingFrame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.ratingFrame.setStyleSheet("")
        self.ratingFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ratingFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ratingFrame.setObjectName("ratingFrame")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.ratingFrame)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.rating15 = QtWidgets.QCheckBox(self.ratingFrame)
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        self.rating15.setFont(font)
        self.rating15.setObjectName("rating15")
        self.gridLayout_8.addWidget(self.rating15, 2, 0, 1, 1)
        self.allRating = QtWidgets.QCheckBox(self.ratingFrame)
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        self.allRating.setFont(font)
        self.allRating.setObjectName("allRating")
        self.gridLayout_8.addWidget(self.allRating, 0, 0, 1, 1)
        self.rating12 = QtWidgets.QCheckBox(self.ratingFrame)
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        self.rating12.setFont(font)
        self.rating12.setObjectName("rating12")
        self.gridLayout_8.addWidget(self.rating12, 1, 0, 1, 1)
        self.Rrated = QtWidgets.QCheckBox(self.ratingFrame)
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        self.Rrated.setFont(font)
        self.Rrated.setObjectName("Rrated")
        self.gridLayout_8.addWidget(self.Rrated, 3, 0, 1, 1)
        self.gridLayout_3.addWidget(self.ratingFrame, 10, 1, 1, 1)
        self.completionFrame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.completionFrame.setStyleSheet("")
        self.completionFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.completionFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.completionFrame.setObjectName("completionFrame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.completionFrame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.completed = QtWidgets.QCheckBox(self.completionFrame)
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        self.completed.setFont(font)
        self.completed.setObjectName("completed")
        self.gridLayout_5.addWidget(self.completed, 0, 0, 1, 1)
        self.notCompleted = QtWidgets.QCheckBox(self.completionFrame)
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        self.notCompleted.setFont(font)
        self.notCompleted.setObjectName("notCompleted")
        self.gridLayout_5.addWidget(self.notCompleted, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.completionFrame, 4, 1, 1, 1)
        self.dayFrame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.dayFrame.setStyleSheet("")
        self.dayFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dayFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dayFrame.setObjectName("dayFrame")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.dayFrame)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.monday = QtWidgets.QCheckBox(self.dayFrame)
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        self.monday.setFont(font)
        self.monday.setObjectName("monday")
        self.gridLayout_7.addWidget(self.monday, 0, 0, 1, 1)
        self.tuesday = QtWidgets.QCheckBox(self.dayFrame)
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        self.tuesday.setFont(font)
        self.tuesday.setObjectName("tuesday")
        self.gridLayout_7.addWidget(self.tuesday, 1, 0, 1, 1)
        self.wednesday = QtWidgets.QCheckBox(self.dayFrame)
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        self.wednesday.setFont(font)
        self.wednesday.setObjectName("wednesday")
        self.gridLayout_7.addWidget(self.wednesday, 2, 0, 1, 1)
        self.thursday = QtWidgets.QCheckBox(self.dayFrame)
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        self.thursday.setFont(font)
        self.thursday.setObjectName("thursday")
        self.gridLayout_7.addWidget(self.thursday, 3, 0, 1, 1)
        self.friday = QtWidgets.QCheckBox(self.dayFrame)
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        self.friday.setFont(font)
        self.friday.setObjectName("friday")
        self.gridLayout_7.addWidget(self.friday, 4, 0, 1, 1)
        self.saturday = QtWidgets.QCheckBox(self.dayFrame)
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        self.saturday.setFont(font)
        self.saturday.setObjectName("saturday")
        self.gridLayout_7.addWidget(self.saturday, 5, 0, 1, 1)
        self.sunday = QtWidgets.QCheckBox(self.dayFrame)
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        self.sunday.setFont(font)
        self.sunday.setObjectName("sunday")
        self.gridLayout_7.addWidget(self.sunday, 6, 0, 1, 1)
        self.gridLayout_3.addWidget(self.dayFrame, 2, 1, 1, 1)
        self.ratingButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.ratingButton.setStyleSheet("background-color: #F3F5F4;\n"
"border-radius: 10px;")
        self.ratingButton.setText("")
        self.ratingButton.setIcon(icon)
        self.ratingButton.setObjectName("ratingButton")
        self.gridLayout_3.addWidget(self.ratingButton, 9, 2, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.search = QtWidgets.QLineEdit(self.mainPage)
        self.search.setGeometry(QtCore.QRect(1250, 10, 321, 41))
        self.search.setObjectName("search")
        self.addAnime = QtWidgets.QPushButton(self.mainPage)
        self.addAnime.setGeometry(QtCore.QRect(360, 10, 112, 34))
        self.addAnime.setStyleSheet("background-color: #335495;\n"
"color: #FEFEFE;")
        self.addAnime.setObjectName("addAnime")
        self.frame = QtWidgets.QFrame(self.mainPage)
        self.frame.setGeometry(QtCore.QRect(0, 240, 341, 1091))
        self.frame.setStyleSheet("background-color: #A5BECF")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(self.mainPage)
        self.layoutWidget.setGeometry(QtCore.QRect(360, 60, 1321, 1001))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.animeFrame6 = QtWidgets.QFrame(self.layoutWidget)
        self.animeFrame6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.animeFrame6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.animeFrame6.setObjectName("animeFrame6")
        self.gridLayout.addWidget(self.animeFrame6, 0, 0, 1, 1)
        self.searchButton = QtWidgets.QPushButton(self.mainPage)
        self.searchButton.setGeometry(QtCore.QRect(1580, 10, 71, 41))
        self.searchButton.setStyleSheet("background-color: #335495;\n"
"color: #FEFEFE;")
        self.searchButton.setObjectName("searchButton")
        self.layoutWidget1 = QtWidgets.QWidget(self.mainPage)
        self.layoutWidget1.setGeometry(QtCore.QRect(840, 1080, 321, 36))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.pageButtonLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.pageButtonLayout.setContentsMargins(0, 0, 0, 0)
        self.pageButtonLayout.setObjectName("pageButtonLayout")
        self.layoutWidget.raise_()
        self.frame.raise_()
        self.filterBox.raise_()
        self.search.raise_()
        self.addAnime.raise_()
        self.layoutWidget.raise_()
        self.searchButton.raise_()
        self.stackedWidget.addWidget(self.mainPage)
        self.popup = QtWidgets.QWidget()
        self.popup.setObjectName("popup")
        self.summary = QtWidgets.QPlainTextEdit(self.popup)
        self.summary.setGeometry(QtCore.QRect(10, 270, 771, 111))
        self.summary.setObjectName("summary")
        self.commentRegister = QtWidgets.QPushButton(self.popup)
        self.commentRegister.setGeometry(QtCore.QRect(690, 390, 91, 61))
        self.commentRegister.setObjectName("commentRegister")
        self.commentInput = QtWidgets.QLineEdit(self.popup)
        self.commentInput.setGeometry(QtCore.QRect(10, 390, 671, 61))
        self.commentInput.setText("")
        self.commentInput.setObjectName("commentInput")
        self.layoutWidget_2 = QtWidgets.QWidget(self.popup)
        self.layoutWidget_2.setGeometry(QtCore.QRect(240, 20, 541, 231))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.insideTitle = QtWidgets.QLabel(self.layoutWidget_2)
        self.insideTitle.setObjectName("insideTitle")
        self.verticalLayout.addWidget(self.insideTitle)
        self.broadcastTime = QtWidgets.QLabel(self.layoutWidget_2)
        self.broadcastTime.setObjectName("broadcastTime")
        self.verticalLayout.addWidget(self.broadcastTime)
        self.company = QtWidgets.QLabel(self.layoutWidget_2)
        self.company.setObjectName("company")
        self.verticalLayout.addWidget(self.company)
        self.genre = QtWidgets.QLabel(self.layoutWidget_2)
        self.genre.setObjectName("genre")
        self.verticalLayout.addWidget(self.genre)
        self.rating = QtWidgets.QLabel(self.layoutWidget_2)
        self.rating.setObjectName("rating")
        self.verticalLayout.addWidget(self.rating)
        self.commentList = QtWidgets.QListWidget(self.popup)
        self.commentList.setGeometry(QtCore.QRect(10, 460, 771, 321))
        self.commentList.setObjectName("commentList")
        self.animeThumbnail = QtWidgets.QLabel(self.popup)
        self.animeThumbnail.setGeometry(QtCore.QRect(10, 10, 211, 251))
        self.animeThumbnail.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.animeThumbnail.setStyleSheet("background-color: rgb(216, 232, 253);\n"
"text-align: center;")
        self.animeThumbnail.setAlignment(QtCore.Qt.AlignCenter)
        self.animeThumbnail.setObjectName("animeThumbnail")
        self.returnToMain = QtWidgets.QPushButton(self.popup)
        self.returnToMain.setGeometry(QtCore.QRect(10, 790, 141, 51))
        self.returnToMain.setStyleSheet("background-color: #335495;\n"
"color: #FEFEFE;")
        self.returnToMain.setObjectName("returnToMain")
        self.stackedWidget.addWidget(self.popup)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.title.setText(_translate("Form", "Filters"))
        self.dayTItle.setText(_translate("Form", "방영 요일"))
        self.completionTitle.setText(_translate("Form", "완결 여부"))
        self.ratingTitle.setText(_translate("Form", "국내 심의 등급"))
        self.genreTitle.setText(_translate("Form", "장르"))
        self.yearTitle.setText(_translate("Form", "방영 연도"))
        self.year2020.setText(_translate("Form", "2020"))
        self.year2019.setText(_translate("Form", "2019"))
        self.year2018.setText(_translate("Form", "2018"))
        self.year2017.setText(_translate("Form", "2017"))
        self.year2016.setText(_translate("Form", "2016"))
        self.loveComedy.setText(_translate("Form", "러브코미디"))
        self.daily.setText(_translate("Form", "일상"))
        self.action.setText(_translate("Form", "액션"))
        self.thriller.setText(_translate("Form", "스릴러"))
        self.fantasy.setText(_translate("Form", "판타지"))
        self.detective.setText(_translate("Form", "추리"))
        self.sport.setText(_translate("Form", "스포츠"))
        self.rating15.setText(_translate("Form", "15세 이상 관람가"))
        self.allRating.setText(_translate("Form", "전체이용가"))
        self.rating12.setText(_translate("Form", "12세 이상 관람가"))
        self.Rrated.setText(_translate("Form", "미성년자 관람불가"))
        self.completed.setText(_translate("Form", "완결"))
        self.notCompleted.setText(_translate("Form", "방영 중"))
        self.monday.setText(_translate("Form", "월요일"))
        self.tuesday.setText(_translate("Form", "화요일"))
        self.wednesday.setText(_translate("Form", "수요일"))
        self.thursday.setText(_translate("Form", "목요일"))
        self.friday.setText(_translate("Form", "금요일"))
        self.saturday.setText(_translate("Form", "토요일"))
        self.sunday.setText(_translate("Form", "일요일"))
        self.addAnime.setText(_translate("Form", "항목 추가"))
        self.searchButton.setText(_translate("Form", "검색"))
        self.commentRegister.setText(_translate("Form", "댓글 등록"))
        self.insideTitle.setText(_translate("Form", "제목, 총 N부작"))
        self.broadcastTime.setText(_translate("Form", "방영 시기"))
        self.company.setText(_translate("Form", "제작사"))
        self.genre.setText(_translate("Form", "장르"))
        self.rating.setText(_translate("Form", "국내 심의 등급"))
        self.animeThumbnail.setText(_translate("Form", "썸네일"))
        self.returnToMain.setText(_translate("Form", "돌아가기"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

